### ISSUE TITLE
Créer une commande permettant d'importer des données texte

### ISSUE THREAD

**Issue by Emmadeliom** [agence-adeliom/lumberjack-project#95]
**Objectif :** 
- lancer une commande dans laquelle on pourrait importer le contenu gutenberg d'une page
- avoir un param id si on veut importer dans une page existante

**Comment by LucasVigneronAdeliom** [comment]
**Idée de la forme que ça pourrait prendre :**
- Une commande prenant différents paramètres :
  - content : _nom du type de contenu / de la classe associée au type de contenu_
  - id : _identifiant du contenu à remplacer (optionnel)_
- Des classes avec une classe parent (par exemple `ImportableContent`)
  - permettrait d'avoir une plus grande maintenabilité si jamais on veut rajouter des features à l'avenir en plus du content, comme un mot de passe ou autre
